name: CI tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tests/**"
      - "circadian_scp_upload/**"
      - "poetry.lock"
      - ".github/workflows/test.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "tests/**"
      - "circadian_scp_upload/**"
      - "poetry.lock"
      - ".github/workflows/test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      # check-out repo and install python
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      # load cache if available
      - name: Load cached venv
        id: cached-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python_version }}-${{ hashFiles('poetry.lock') }}

      # install poetry if venv not in cache
      - name: Install Poetry
        if: steps.cached-venv.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        if: steps.cached-venv.outputs.cache-hit != 'true'
        run: poetry install --with=dev

      # run test suite
      - name: Run pytests
        env:
          TEST_SERVER_HOST: ${{ secrets.TEST_SERVER_HOST }}
          TEST_SERVER_USERNAME: ${{ secrets.TEST_SERVER_USERNAME }}
          TEST_SERVER_PASSWORD: ${{ secrets.TEST_SERVER_PASSWORD }}
        run: |
          source .venv/bin/activate
          pytest --verbose --capture=no --cov=circadian_scp_upload tests/
